version: '3.8'

services:
  # Servicio de Base de Datos (Agregado para cumplir con Persistencia y Volúmenes)
  db_mysql:
    container_name: db_mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Contraseña del admin de BD
      MYSQL_DATABASE: ${DB_NAME:-innovatech}
      MYSQL_USER: ${DB_USERNAME:-usuario}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/mysql # <-- AQUÍ SE CUMPLE EL CRITERIO DE PERSISTENCIA
    networks:
      - app_network
    restart: always

  # Servicio 1: API de Ventas
  api_ventas:
    container_name: api_ventas
    image: caypereira/api_ventas:latest
    ports:
      - "9080:8080"
    environment:
      - DB_ENDPOINT=db_mysql # Se conecta al nombre del contenedor de la BD
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-innovatech}
      - DB_USERNAME=${DB_USERNAME:-usuario}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    depends_on:
      - db_mysql
    networks:
      - app_network
    restart: always

  # Servicio 2: API de Despachos
  api_despachos:
    container_name: api_despachos
    image: caypereira/api_despachos:latest
    ports:
      - "9082:8081"
    environment:
      - DB_ENDPOINT=db_mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-innovatech}
      - DB_USERNAME=${DB_USERNAME:-usuario}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    depends_on:
      - db_mysql
    networks:
      - app_network
    restart: always

  # Servicio 3: Frontend Web
  frontend_app:
    container_name: frontend_despacho
    image: caypereira/frontend_despacho:latest
    ports:
      - "9000:80"
    depends_on:
      - api_ventas
      - api_despachos
    networks:
      - app_network
    restart: always

# Declaración de la red interna
networks:
  app_network:
    driver: bridge

# Declaración del volumen (named volume) para la persistencia
volumes:
  db_data:
    driver: local