name: CI/CD Pipeline - Evaluacion 2

on:
  push:
    branches: ["main", "deploy"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código del Repositorio
        uses: actions/checkout@v4

      - name: Autenticarse en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 1. Construir y subir API Ventas
      - name: Build & Push API Ventas
        uses: docker/build-push-action@v5
        with:
          context: ./back-Ventas_SpringBoot/Springboot-API-REST
          file: ./back-Ventas_SpringBoot/Springboot-API-REST/Dockerfile
          push: true
          tags: caype/api_ventas:latest

      # 2. Construir y subir API Despachos
      - name: Build & Push API Despachos
        uses: docker/build-push-action@v5
        with:
          context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          file: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO/Dockerfile
          push: true
          tags: caype/api_despachos:latest

      # 3. Construir y subir Frontend
      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front_despacho
          file: ./front_despacho/Dockerfile
          push: true
          tags: caype/frontend_despacho:latest